export const VISIBILITY_FILTER_SET = 'VISIBILITY_FILTER_SET';

export const VISIBILITY_FILTER_STATE_SHOW_ALL =
  'VISIBILITY_FILTER_STATE_SHOW_ALL';
export const VISIBILITY_FILTER_STATE_SHOW_ACTIVE =
  'VISIBILITY_FILTER_STATE_SHOW_ACTIVE';
export const VISIBILITY_FILTER_STATE_SHOW_COMPLETED =
  'VISIBILITY_FILTER_STATE_SHOW_COMPLETED';

export function visibilityFilterSet(filter) {
  return {
    type: VISIBILITY_FILTER_SET,
    filter,
  };
}
